### ISSUE TITLE
Tiles overlapping

### ISSUE THREAD

**Issue by ivanstan** [TNOCS/geojson-tile-server#3]
I'm using google maps to display data layer on it, geojson is served using tile server, however the issue is that data layer is transparent and overlapping of tiles is visible. Any suggestions why this happens?

<img width="1024" alt="Screenshot 2019-06-25 18 52 28" src="https://user-images.githubusercontent.com/1379480/60117502-7702fe80-977a-11e9-8e82-e64c29ba453a.png">

**Comment by Craytor** [comment]
This is rather interesting.

Couple questions:
1.) Can you share example json that you are using?
2.) Can you provide an example of your client (web map) within a jsfiddle or similar?

**Comment by ivanstan** [comment]
Thanks on such quick response.
I'm using a google map and loading tiles on idle event, this is how my code looks like:

```
google.maps.event.addListener(this.map, 'idle', () => {
    const zoom = this.map.getZoom();
    const center = this.map.getCenter();

  const [x, y, z] = globalMercator.lngLatToGoogle([center.lng(), center.lat()], zoom);

  this.map.data.loadGeoJson(`http://localhost:8123/pinus-nigra/${z}/${x}/${y}.geojson`);
});
```
I'm using this library to get tile based on LatLng https://www.npmjs.com/package/global-mercator
And here is the file: http://cdn.ivanstanojevic.me/data/pinus-nigra.geojson

I hope I will be able to provide jsfiddle soon.

**Comment by erikvullings** [comment]
I assume the reason is that the geojson-vt, which is the lib responsible for creating the tiles, uses a [buffer of a number of pixels](https://github.com/TNOCS/geojson-tile-server/blob/ec61aeb3d15ddbe79fd0a98840de093850cbb6e2/src/utils.ts#L47). When using the geojson as an overlay, that makes sense, but not when it is used as a base map.

Easiest way is probably to add a new option in cli.ts, allowing you to specify the buffer size, and passing that through. A quick and dirty test is to set it manually in the generated js file and see if it fixes the problem. 
If so, can you create a pull request for that?

**Comment by ivanstan** [comment]
I did exactly what you said and indeed this helped, setting a buffer size to 0 shows no overlapping. I will try to add option to cli and submit the PR in the following days. Thanks
