### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by ivanstan** [TNOCS/geojson-tile-server#5]
I'm serving three geojson files each of ~80MB. After starting geojson server, memory consumption quickly gets up to ~1.5GB. Should it really be this high or there are any known memory leaks I should look to?
`ps aux` output bellow
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
-------- 2858592  0.0  0.6 1455536 874392 ?      Sl   Jun29   0:31 /home/-------/bin/node ./node_modules/geojson-tile-server/dist/cli.js --data data/
```

**Comment by erikvullings** [comment]
It may depend a bit on your settings and usage, but the underlying [geojson-vt](https://github.com/mapbox/geojson-vt) library really likes memory: it pre-computes the tiles up to a certain zoom level, and will cache the tiles you have requested. Worst case scenario is that for each zoom level, you need more than 80Mb (why do I say more - since there is a 60pix overlap between tiles, and rendering separate tiles also brings in some overhead). Although this will not occur for the lower zoom levels (world/country level), it will for the detailed ones.
A simple computation yields 3x80 = 240Mb, so if the cache contains higher zoom layers, 1.5Gb is not unfeasible.

**Comment by ivanstan** [comment]
Well if that's the case there's not much we can.

**Comment by erikvullings** [comment]
Indeed, I'm afraid so... you might raise the issue with geojson-vt, though...
